version: '3.8'

services:
  odoo19:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo19:latest
    container_name: odoo19
    ports:
      - "8069:8069"  # Odoo 19 di port 8069
      - "8072:8072"
    environment:
      - HOST=host.docker.internal
      - PORT=5432
      - DB_USER=odoo19
      - DB_PASSWORD=""
      - DB_NAME=odoo19
      - ADMIN_PASSWORD=admin123
    command: odoo -c /etc/odoo/odoo.conf
    entrypoint: []
    volumes:
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo
      - ./config:/etc/odoo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
