[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$j7H2PqdUylmL8T6H0PofoQ$GiHVc8T5bRUP8/2VyPExLvl5qQFvlBdP5rCQJGWcqXvtq5YnXvpBc0ZLdVh2fYsj6WKZQM0rGZ5nR8yI7nKJNA
db_host = host.docker.internal
db_port = 5432
db_user = odoo19
db_password = False
dbfilter = ^odoo19$
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
